CREATE TABLE IF NOT EXISTS `user_message`(
    `id` INT(4) NOT NULL AUTO_INCREMENT COMMENT 'ID', 
    `username` VARCHAR(30) NOT NULL DEFAULT '匿名' COMMENT '姓名',
    `pwd` VARCHAR(20) NOT NULL DEFAULT '123456' COMMENT '密码',
    PRIMARY KEY(`id`)
)ENGINE = INNODB DEFAULT CHARSET = utf8




